### ISSUE TITLE
 `FlagEmbeddingReranker` OSError

### ISSUE THREAD

**Issue by ggjx22** [run-llama/llama_parse#85]
I have a successful end-to-end test of the [`demo_advanced.ipynb`](https://github.com/run-llama/llama_parse/blob/main/examples/demo_advanced.ipynb) using my own pdf files when executing the codes in jupyter notebook environment. So I write my own functions to encapsulate the codes and moved them to a python file (let's call this file utility_gpt_rag.py). I call my functions within jupyter notebook which still works fine, but not working when I call the functions from another python file (let's call this main_document_understanding.py).

The errors mention things like being authenticated with HuggingFace and the repo being private or not. These was not covered in the demo notebook or any or the tutorials on YouTube. Did anyone encounter a similar issue when executing the code from a python file?

This is the error traceback messages:
```
Traceback (most recent call last):
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/BBAI/bge-reranker-large/resolve/main/tokenizer_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\file_download.py", line 1403, in hf_hub_download
    raise head_call_error
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\file_download.py", line 1667, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\file_download.py", line 409, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-65f41745-40a3fa9e02ab0aa4589fafb6;ad44574d-642a-4a63-aae5-17c14136388d)

Repository Not Found for url: https://huggingface.co/BBAI/bge-reranker-large/resolve/main/tokenizer_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\agpgago\data-science\document-automation-wizard\main_document_understanding.py", line 60, in <module>
    email_data = extract.extract_workflow(emails, container_name, folder_path)
  File "C:\Users\agpgago\data-science\document-automation-wizard\app\workflow_extract.py", line 81, in extract_workflow
    query_engine = llama.query_engine_w_ranker(embeddings)
  File "C:\Users\agpgago\data-science\document-automation-wizard\utility\utility_gpt_rag.py", line 58, in query_engine_w_ranker
    reranker = FlagEmbeddingReranker(top_n=2, model='BBAI/bge-reranker-large')
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\llama_index\postprocessor\flag_embedding_reranker\base.py", line 30, in __init__
    self._model = FlagReranker(
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\FlagEmbedding\flag_models.py", line 133, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 767, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 600, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\Users\agpgago\data-science\document-automation-wizard\.venv\lib\site-packages\transformers\utils\hub.py", line 421, in cached_file
    raise EnvironmentError(
OSError: BBAI/bge-reranker-large is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```

Package versions:
```
FlagEmbedding @ git+https://github.com/FlagOpen/FlagEmbedding.git@5d43be378200e728ea9f32d552e7a125d8496c94
huggingface-hub==0.21.4
llama-index==0.10.19
llama-index-agent-openai==0.1.5
llama-index-cli==0.1.8
llama-index-core==0.10.19
llama-index-embeddings-openai==0.1.6
llama-index-indices-managed-llama-cloud==0.1.3
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.7
llama-index-multi-modal-llms-openai==0.1.4
llama-index-postprocessor-flag-embedding-reranker==0.1.2
llama-index-program-openai==0.1.4
llama-index-question-gen-openai==0.1.3
llama-index-readers-file==0.1.8
llama-index-readers-llama-parse==0.1.3
llama-index-vector-stores-chroma==0.1.5
llama-parse==0.3.8
llamaindex-py-client==0.1.13
openai==1.3.9
```

**Comment by hatianzhang** [comment]
I think it seems like your flag emb reranker is not set up correctly. since it works for some of your py files.
pls ensure your env has it installed ```pip install llama-index-postprocessor-flag-embedding-reranker
```

**Comment by ggjx22** [comment]
no, `llama-index-postprocessor-flag-embedding-reranker` has already been set up and installed correctly in my virtual env. But the error still persist.

**Comment by ggjx22** [comment]
update: issue can be closed. turns out I made a spelling mistake in the name of the repo!

mistake: `model='BBAI/bge-reranker-large'`
correction: `model='BAAI/bge-reranker-large'`
